#!/bin/bash

TABS_URL='https://extdist.wmflabs.org/dist/extensions/Tabs-REL1_37-e8fb792.tar.gz'
TABS_ZIP='Tabs.tar.gz'
TABS_EXT_DIR='Tabs'

TABBERNEUE_URL='https://github.com/StarCitizenTools/mediawiki-extensions-TabberNeue/archive/main.zip'
TABBERNEUE_ZIP='TabberNeue.zip'
TABBERNEUE_EXT_DIR='TabberNeue'

TREEANDMENU_URL='https://gitlab.com/Aranad/TreeAndMenu/-/archive/master/TreeAndMenu-master.tar.gz'
TREEANDMENU_ZIP='TreeAndMenu.tar.gz'
TREEANDMENU_EXT_DIR='TreeAndMenu'

DISPLAYTITLE_URL='https://github.com/wikimedia/mediawiki-extensions-DisplayTitle/archive/refs/tags/3.1.tar.gz'
DISPLAYTITLE_ZIP='DisplayTitle.tar.gz'
DISPLAYTITLE_EXT_DIR='DisplayTitle'

DOCKER_IMAGE_NAME='aldrin/mediawiki'

downloadArchive() {
	local archiveFileName=$1
	local downloadUrl=$2
	local targetDir=$3
	if [[ -f ${archiveFileName} ]]; then
		echo "Found ${archiveFileName} extension file."
	else
		echo "${archiveFileName} extension file not found. Downloading..."
		wget -q -O $archiveFileName $downloadUrl
		if (( $? )); then
			echo "Failed to download extension."
			echo "Aborting docker image build."
			exit 1
		else
			echo "Downloaded $archiveFileName successfully."
			extractArchive $archiveFileName $targetDir
		fi
	fi
}

extractArchive() {
	local archiveFileName=$1 
	local targetDir=$2
	local sourceDir=""
	if [[ "$archiveFileName" =~ "tar.gz" ]]; then
                sourceDir=$(tar tzf $archiveFileName | sed -e 's@/.*@@' | uniq)
		tar --overwrite -xf $archiveFileName
	else
		sourceDir=$(unzip -qql $archiveFileName | awk '{print $4}' | sed -e 's@/.*@@' | uniq)
		unzip -q -o $archiveFileName
	fi
	if (( $? )); then
		echo "Failed to extract archive file."
		echo "Aborting docker image build."
		exit 1
	else
		echo "Extracted $archiveFileName successfully."
		if [[ ! -z "$sourceDir" ]] && [[ ! -z "$targetDir" ]]; then
			rm -rf $targetDir
			mv $sourceDir $targetDir
		fi
	fi
}

clear
echo "Building docker image"
echo ""
downloadArchive ${TABS_ZIP} ${TABS_URL}
downloadArchive ${TABBERNEUE_ZIP} ${TABBERNEUE_URL} ${TABBERNEUE_EXT_DIR} 
downloadArchive ${TREEANDMENU_ZIP} ${TREEANDMENU_URL} ${TREEANDMENU_EXT_DIR}
downloadArchive ${DISPLAYTITLE_ZIP} ${DISPLAYTITLE_URL} ${DISPLAYTITLE_EXT_DIR}
echo ""

docker build -t ${DOCKER_IMAGE_NAME} .

#::END::


